import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Dock } from "@/components/Dock";
import { Nav } from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                  {/* Responsive Navbar */}
                  <div className="w-full px-5 py-3 md:px-10 md:py-5 flex justify-between items-center">
            {/* Add more divbar content here */}
            <Nav />
          </div>
        {children}
        <div className="w-full fixed bottom-5 left-0 z-10"><Dock/></div>
      </body>
    </html>
  );
}
